# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def all_pods
  pod 'ObjectMapper'
end

target 'HA_Coding_Ex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  all_pods

  target 'HA_Coding_ExTests' do
    inherit! :search_paths
  end

  target 'HA_Coding_ExUITests' do
  end

end
